- .travis.yml
- bin/install-package-tests.sh
- composer.json
- search-replace-command.php
Doing so ensures tests run against local copy of command, instead of
Phar bundled version.
See https://github.com/wp-cli/wp-cli/issues/3850#issuecomment-288719442
> Use Composer to install WP-CLI in tests

- README.md
- features/search-replace.feature
- src/Search_Replace_Command.php
Addresses #13, adds news option `--format` that accepts either `table` or `count`, with `table` being the default.
> Use `--format=count` to only show number of rows affected

- features/search-replace-export.feature
Adds `suppress-error-log.php` to `search-replace-export.feature:154` stop notice getting written to `error_log`.
> Suppress error in search-replace-export.feature.

- .gitignore
- features/search-replace-export.feature
- features/search-replace.feature
- src/Search_Replace_Command.php
PR https://github.com/wp-cli/search-replace-command/pull/4
Adds `esc_sql_ident()` func to backtick column/table names and uses it throughout, though the only real fixes (excluding the unlikely case of backticks in column/table names) is in `php_handle_col()`, where primary keys weren't escaped, as mentioned in the original PR, and `esc_sql()`was used for `$col_sql`.
(A similar fix needs to be done for `db search`.)
Also adds note about the double escaping in the WP <= 3.9 part of `esc_like()` which I thought was wrong but turns out to be necessary.
> Add esc_sql_ident(), catering for reserved word column names.

- features/search-replace-export.feature
- src/Search_Replace_Command.php
PR https://github.com/wp-cli/search-replace-command/pull/16
Suppresses PHP Notice on `fopen()` export file and reverts https://github.com/wp-cli/search-replace-command/pull/16 which suppressed PHP Notices in the test - ie the proper fix.
> Suppress error on fopen export file, revert PR #16.

- composer.json
- features/search-replace.feature
- src/Search_Replace_Command.php
- src/WP_CLI/SearchReplacer.php
`wp db search` supports `--regex-delimiter`, so this command will be better to support it too.
> Add `--regex-delimiter`

- features/search-replace.feature
- src/Search_Replace_Command.php
- src/WP_CLI/SearchReplacer.php
If regex is `/`, regex will be escaped like following.
```
http:\/\/example.com
```
> Improve validation for `--regex-flags` and `--regex-delimiter` and add tests for them

- features/search-replace-export.feature
- features/search-replace.feature
- src/Search_Replace_Command.php
The `LIKE` on the SQL query when doing a dry run needs to be case sensitive to report changes and count properly (as `REPLACE` is case sensitive).
So changes `LIKE` to cast search string to `BINARY`.
Also fixes plural of successful replacements message when only one replacement.
> Make dry run SQL LIKE query case sensitive.

- features/search-replace-export.feature
- features/search-replace.feature
- src/Search_Replace_Command.php
- src/WP_CLI/SearchReplacer.php
Fixes #1
Adds logging of before/after changes.
> Add logging of search-replace transformations.

- features/search-replace.feature
- src/Search_Replace_Command.php
From https://github.com/wp-cli/db-command/pull/56
> Avoid displaying default delimiter on regex fail

- features/search-replace-export.feature
- src/Search_Replace_Command.php
> Fix: Changed behaviour of esc_sql() in WordPress 4.8.3

- README.md
- features/search-replace-export.feature
- features/search-replace.feature
- src/Search_Replace_Command.php
- Implemented a method to exclude tables by adding a new argument `--skip-tables`
> Add `--skip-tables=<tables>` argument to exclude tables when performing search-replace

- src/Search_Replace_Command.php
> Remove unnecessary `array_diff()`; skipping within loop is clearer

- README.md
- composer.json
- src/Search_Replace_Command.php
Per wp-cli/wp-cli#4542, this PR converts help docs for search-replace subcommands to use third-person singular verbs.
> Convert search-replace subcommand help summaries to use third-person singular verbs.

- src/Search_Replace_Command.php
- Fix for The report prints a message when the table's primary key isn't found
Fixes #53
> Do not show on report tables without index when using --report-change-only

- features/search-replace-export.feature
- features/search-replace.feature
Related https://github.com/wp-cli/wp-cli/pull/4624
Adjusts tests to be compatible with `utils\wp_get_table_names()`.
This will have to be merged into https://github.com/wp-cli/search-replace-command/pull/59 for its tests to pass.
> Adjust tests for wp_get_table_names changes.

- features/search-replace.feature
- src/Search_Replace_Command.php
Related https://github.com/wp-cli/search-replace-command/pull/59 and https://github.com/wp-cli/search-replace-command/issues/58
Allows for BIGINTs in `esc_sql_value()` which are > PHP_INT_MAX.
> Allow for BIGINTs in esc_sql_value().

- composer.json
- features/bootstrap/FeatureContext.php
- features/bootstrap/Process.php
- features/bootstrap/utils.php
- utils/behat-tags.php
Refreshes test suite and normalizes composer.json, requiring `wp-cli/wp-cli` ^1.5.
1.1.5 pre-release changes for WP-CLI 1.5.0.
> v1.1.5 prerelease: refresh test suite, require wp-cli ^1.5.

- src/WP_CLI/SearchReplacer.php
We leave the content untouched (instead of replacing with `null`) and issue a warning.
This is far from ideal, as it can potentially spam the screen full of warnings. However, a better mechanism will require a total refactor of the `SearchReplacer` class.
Fixes #65
> Handle PCRE errors gracefully

- features/search-replace.feature
- src/WP_CLI/SearchReplacer.php
When an unknown class is deserialized, we just throw a warning an avoid making a change, due to the lack of full knowledge of the class.
This also makes sure we don't throw a notice on PHP 7.2, which changed how `is_object()` deals with `_PHP_Incomplete_Class`.
Fixes #68
> Handle incomplete class (un)serialization gracefully

- features/search-replace.feature
- src/Search_Replace_Command.php
- src/WP_CLI/SearchReplacer.php
> Add --regex-limit option.

- features/search-replace-export.feature
- src/Search_Replace_Command.php
The code that exports a search-replace command as SQL creates a prepared
statement where all columns values are assumed to be strings. Normally
this is fine as MySQL/MariaDB will do the conversion work at import.
However, in some cases, a column may allow nulls in a numeric field.
In this instance, the call to `prepare` will translate a null value into
null string. Importing will then fail as null string is not a numeric
value.
This patch replaces the original code that assumed strings for all bind
parameters. Each column value is iterated over and inspected. If the
value is not NULL, the value is added to the `$values` array and a bind
parameter, `%s` is added to a substituions array. If the value causes
`is_null` to return true, only 'NULL' is added to the substituions
array.
The code …
> Corrects NULL export values.

- src/WP_CLI/SearchReplacer.php
Fixes relate to the following rules:
* Always specify visibility for all class properties and methods.
> PHPCS: fix up the code base [2] - scope modifiers

- src/Search_Replace_Command.php
Fixes relate to the following rules:
* Each argument in a multiline function call should start on a new line.
Note: in the (near?) future, multi-line arguments in function calls will also be prohibited.
This will impact this code.
The choice for the future is:
* Either change the closures to full-blown methods.
* Declare each before their respective function call, assign them to a variable and pass the variable to the function call.
Note: this commit will be easiest to review by ignoring whitespace changes.
> PHPCS: fix up the code base [6] - multi-line function calls

- src/Search_Replace_Command.php
Multi-line function calls need to have each argument on a new line.
In a next iteration of this principle, it is expected that a sniff will be introduced to ban multi-line function call arguments.
With this mind, this function call with multi-line parameters which was already causing errors to be thrown by PHPCS, has been fixed by moving multi-line function call arguments out of the function call and defining these as a variable before passing it to the function call.
The multiple nested function calls have also been unnested.
> PHPCS: fix up the code base [5] - multi-line function calls

- src/Search_Replace_Command.php
- src/WP_CLI/SearchReplacer.php
Fixes relate to the following rules:
* Use strict comparisons.
* Use the `$strict` parameter when calling `in_array()`.
> PHPCS: fix up the code base [3] - strict comparisons

- README.md
- src/Search_Replace_Command.php
Google owns and sells the `.dev` TLD, and .dev domains have strict HSTS enforcements, so use `.test` instead which is protected by an RFC, and has no restrictions on what kind of IPs it can be mapped to
> Swapped out the .dev Google TLD for the .test RFC protected domain in doc examples

- src/Search_Replace_Command.php
Variable names should be in `snake_case`.
As this is a function local variable, it can be safely renamed without BC
> PHPCS: fix up the code base [8] - rename a local variable

- src/WP_CLI/SearchReplacer.php
Fixes relate to the following rules:
* Declare only one property per statement.
> PHPCS: fix up the code base [9] - one property per statement

- src/Search_Replace_Command.php
I originally meant to turn the loose comparison into a strict one here, but afaict, the condition is useless, as we already have the opposite check with a `continue` above. It would always be true anyway.
> Remove unneeded condition

- src/Search_Replace_Command.php
Because we are doing a lot of manual assembly of SQL strings, PHPCS & WPCS do not pick up on all the actual escaping that is happening.
I went through all statements and made sure that they all escape as needed before whitelisting them.
> Verify and whitelist SQL escaping

- .distignore
- .gitignore
- composer.json
- phpcs.xml.dist
- src/Search_Replace_Command.php
- src/WP_CLI/SearchReplacer.php
This basically adds a PHPCS ruleset using the new WPCliCSstandard and adds a few select whitelist comments.
Please see the individual commits for more detail.
The build for this PR won't be able to pass until wp-cli-tests 2.1 has been released, upon which time, the build can just be restarted and should be green ;-)
Fixes #114
> Implement CS checking based on the WPCliCS ruleset

- README.md
- features/search-replace-export.feature
- features/search-replace.feature
- src/Search_Replace_Command.php
This little PR permits to use wildcards in `skip-tables` option like this : `--skip-tables=wp_post*`.
Useful for example when we want to skip a plugin's tables which begin by a prefix
> Adds wildcards support to skip-tables parameter

- features/search-replace.feature
- src/Search_Replace_Command.php
ref: https://github.com/wp-cli/search-replace-command/issues/66
Get error message from `error_get_last()` , and display it on STDERR.
> Improve error message on regex check

- composer.json
- src/WP_CLI/SearchReplacer.php
> Only try to unserialize strings

- features/search-replace.feature
- src/Search_Replace_Command.php
In #153 the `--precise` queries were chunked to avoid loading the entire DB into memory and thus risking OOM issues.
However, the replacement is happening within each chunk, which breaks the `$offset` handling, causing every second chunk to be missed. This makes it necessary to run a query multiple times to ensure all occurrences are replaced.
This PR defers the actual updates until after the full search. This is still worse in terms of memory management that completely isolated chunking, but it should still be an overall improvement while making the replacements in a reliable way.
Fixes #157
> Fix offset handling when doing chunked replaces

- composer.json
- features/search-replace.feature
Set a `blogdescription` in tests after it was set to empty string in WordPress core https://github.com/WordPress/wordpress-develop/commit/66dba67484a2e0aaa7bcafc0fa70b33d64448f74 this fixes test failure in https://github.com/wp-cli/automated-tests/runs/7797876665?check_suite_focus=true#step:14:64
> Restore blogdescription to fix test

- src/WP_CLI/SearchReplacer.php
Under some circumstances, the error suppression operator (`@`) is not enough to keep the `unserialize` from throwing warnings or notices. These then end up in the exported SQL file and corrupt the replacements.
This PR changes the error reporting levels globally for the `unserialize` call to get rid of these unwanted notices and warnings.
> Add further suppression of warnings and notices

- src/Search_Replace_Command.php
When using wp-sqlite-db as the back end for WordPress, wpcli's `search-replace` command fails because wp-sqlite-db returns text column types as `TEXT`, and wpcli search-replace checks whether a column is textual in `is_text_col` with `strpos` for "text" or "varchar". If this were `stripos` instead of `strpos` then this problem would be resolved, which would be nice, and I don't believe there would be any backward compatibility implications. So, here's a one-character PR :-)
(Of course, sqlite as backend isn't actually supported, but this is a fairly small change which should make things better for that without affecting the mainline code. I've also proposed https://github.com/aaemnnosttv/wp-sqlite-db/pull/56 to wp-sqlite-db to have that return lowercase "text" for column types as well, …
> Make is_text_col's search case-insensitive for sqlite support

- features/search-replace.feature
It looks like the invalid-regex-delimiter test is failing under PHP 8.2. This was noticed because of [a failing test under another PR](https://github.com/wp-cli/search-replace-command/actions/runs/4931033960/jobs/8812678858?pr=180)(#180).
This PR fixes the test to deal with a changing preg_match() error message in PHP 8.2.
Behat is new to me, so perhaps there is a better way to approach this. But hopefully this is helpful.
> Fix regex invalid delimiter test for PHP 8.2

- features/search-replace.feature
- src/Search_Replace_Command.php
This change makes PHP replacement queries and memory usage more efficient in order to address issues we've encountered with long-running queries and OOM conditions with certain sites.
It improves the primary key SELECT queries by eliminating the use of OFFSET because OFFSET requires that the database consider all rows up to OFFSET before taking rows up to the LIMIT. This can make queries become slower as OFFSET increases. The new SELECT query relies on primary key conditions to more efficiently eliminate previous rows from consideration. This way, the database can use an index to identify rows with keys greater than those of the previous chunk and then take rows from that set up to the LIMIT.
It improves memory usage by doing updates along the way rather than storing all a column's …
> Address long-running queries and OOM contributor in PHP replacement

- features/search-replace.feature
- src/Search_Replace_Command.php
Fixes #182 
This PR addresses two bugs:
1. When a table has a composite key, precise and regex search-replace fails because of a SQL syntax error.
2. Once the cause of the SQL syntax error was addressed, there was another bug where, for a composite key (X, Y, Z) the next batch conditions were always X > lastX AND Y > lastY AND Z > lastZ. This condition can skip rows when ordering by X, Y, and Z because Y and Z may repeat values within different values of X. If we assume Y and Z always increase independently of one another, we will skip rows where previous Y and Z values repeat under subsequent values of X.
There are three commits under this PR. The first adds tests that will fail until the next two commits are applied. Please note that number of rows INSERTed for testing with composite …
> Fix search-replace for tables with composite primary keys

- features/search-replace-export.feature
- features/search-replace.feature
- src/Search_Replace_Command.php
- src/WP_CLI/SearchReplacer.php
As discussed in the following issue thread: https://github.com/wp-cli/search-replace-command/issues/191
PHP 8.1 made it so class objects deserialized from strings must follow the types defined on the class if it has been loaded prior. Else you will face a PHP fatal TypeError:
```
PHP Fatal error:  Uncaught TypeError: Cannot assign null to property mysqli_result::$current_field of type int in phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php:90
```
This approach is to `catch` those `TypeError`s when they happen, warn the user about it but then continue the S&R process. The only con to this approach that I can see is that `TypeError` [according to PHP's own docs](https://www.php.net/manual/en/class.typeerror.php) doesn't exist in PHP 5.6 but running …
> Skip search and replace on objects that can't deserialize safely

- src/Search_Replace_Command.php
If I use the search-replace command `wp search-replace 'aaa' 'bbb' wp_users --format=table --verbose --dry-run` with WP CLI 2.9.0 and PHP 8.2.14, I get the warning:
`Deprecated: Creation of dynamic property Search_Replace_Command::$start_time is deprecated in /vendor/wp-cli/search-replace-command/src/Search_Replace_Command.php on line 381`
This PR fixes the warning.
> PHP 8.2 Deprecation: Fix creation of dynamic property.

- features/search-replace-export.feature
Improve the test case after https://core.trac.wordpress.org/changeset/58105 to address failures.
Simply removes the bits with the autoload value from the assertions.
The alternative would be to use a different value depending on the WP version but that seems overkill.
> Fix tests after change in WordPress trunk

- features/search-replace-export.feature
`siteurl` is not necessarily the first row in `wp_options`.
It appears that other options such as `cron` can be first.
This removes the option ID from the assertion, as it is not relevant.
We only want to verify that the site URL changed.
> Fix test for WordPress trunk
